name: Build test
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12
      id: go
      
    - name: Set up system dependencies
      run: sudo apt install -y libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev
      
    - name: Set up GOPATH
      run: mkdir -p go/src/github.com

    - name: Check out Rurik source code
      run: cd go/src/github.com && git checkout $GITHUB_SHA

    - name: Get dependencies
      env:
        GOPATH: ~/runner/work/rurik/go
      run: cd src/demo && go get -v ./...

    - name: Build
      run: go build -v src/demo/*.go
